/**
 * Filterable patient resource library (education links + site content).
 */
window.IBDPAL_RESOURCES = [
  { title: 'IBD Blog (all articles)', category: 'getting-started', type: 'site', url: '/blog', tags: ['articles', 'nutrition', 'flare'] },
  { title: 'IBD Support by State', category: 'community', type: 'site', url: '/support', tags: ['local', 'map'] },
  { title: 'IBD FAQ', category: 'getting-started', type: 'site', url: '/faq', tags: ['questions'] },
  { title: 'IBD Flare Help Hub', category: 'wellness', type: 'site', url: '/flare-help', tags: ['flare'] },
  { title: 'Teens & School Hub', category: 'family', type: 'site', url: '/teens-and-school', tags: ['teen', '504'] },
  { title: 'Ulcerative Colitis Hub', category: 'getting-started', type: 'site', url: '/ulcerative-colitis', tags: ['colitis'] },
  { title: 'Crohn\'s Disease Hub', category: 'getting-started', type: 'site', url: '/crohns-disease', tags: ['crohn'] },
  { title: 'IBD Nutrition Hub', category: 'nutrition', type: 'site', url: '/ibd-nutrition', tags: ['food', 'diet'] },
  { title: 'IBD Patient Guides (by topic)', category: 'getting-started', type: 'site', url: '/guides', tags: ['search', 'crohn', 'colitis', 'diet', 'flare'] },
  { title: 'IBD Crohn\'s Support Guide', category: 'community', type: 'site', url: '/ibd-crohns-support', tags: ['support', 'national'] },
  { title: 'Newly Diagnosed with IBD', category: 'getting-started', type: 'site', url: '/newly-diagnosed', tags: ['crohn', 'colitis', 'beginner'] },
  { title: 'Doctor Visit Prep Checklist', category: 'getting-started', type: 'site', url: '/visit-prep', tags: ['clinic', 'printable'] },
  { title: 'Community Map by State', category: 'community', type: 'site', url: '/support', tags: ['local', 'map'] },
  { title: 'Pediatric & Caregiver Hub', category: 'family', type: 'site', url: '/pediatric-caregivers', tags: ['kids', 'parents'] },
  { title: 'Patient Stories', category: 'community', type: 'site', url: '/patient-stories', tags: ['peer'] },
  { title: 'For Clinicians | Visit Summaries', category: 'clinical', type: 'site', url: '/for-clinicians', tags: ['export', 'doctor'] },
  { title: 'Clinical Partnerships', category: 'clinical', type: 'site', url: '/clinical-partnerships', tags: ['hospital'] },
  { title: 'CCF IBD Help Center', category: 'community', type: 'external', url: 'https://www.crohnscolitisfoundation.org/live-full/live-full-ibd-help-center', tags: ['helpline', 'national'] },
  { title: 'CCF Find a Support Group', category: 'community', type: 'external', url: 'https://www.crohnscolitisfoundation.org/find-a-support-group', tags: ['peer'] },
  { title: 'ImproveCareNow Families', category: 'family', type: 'external', url: 'https://www.improvecarenow.org/patients-parents', tags: ['pediatric'] },
  { title: 'GIKids', category: 'family', type: 'external', url: 'https://gikids.org/', tags: ['pediatric'] },
  { title: 'UOAA Ostomy Support', category: 'community', type: 'external', url: 'https://ostomy.org/', tags: ['ostomy'] },
  { title: 'FODMAP Diet for Crohn\'s & Colitis', category: 'nutrition', type: 'blog', url: '/blog/fodmap-diet-crohns-colitis', tags: ['food', 'fodmap', 'diet'] },
  { title: 'Anti-Inflammatory Diet & IBD', category: 'nutrition', type: 'blog', url: '/blog/anti-inflammatory-diet-ibd', tags: ['food', 'diet'] },
  { title: 'High-Protein IBD Meal Ideas', category: 'nutrition', type: 'blog', url: '/blog/protein-meal-plan-ibd-remission', tags: ['food', 'protein', 'meal plan'] },
  { title: 'Teen Nutrition & IBD Growth', category: 'nutrition', type: 'blog', url: '/blog/teen-nutrition-ibd-growth', tags: ['teen', 'food', 'growth'] },
  { title: 'Iron, B12 & Vitamin D With IBD', category: 'nutrition', type: 'blog', url: '/blog/iron-b12-vitamin-d-ibd', tags: ['vitamins', 'health'] },
  { title: 'High School With Crohn\'s or Colitis', category: 'family', type: 'blog', url: '/blog/high-school-ibd-survival-guide', tags: ['teen', '504', 'school'] },
  { title: 'Social Life & Dating (Teens)', category: 'family', type: 'blog', url: '/blog/social-life-dating-teens-ibd', tags: ['teen', 'mental health'] },
  { title: 'Exercise With IBD', category: 'wellness', type: 'blog', url: '/blog/exercise-physical-activity-ibd', tags: ['exercise', 'sports', 'health'] },
  { title: 'Best Foods During a Crohn\'s Flare', category: 'nutrition', type: 'blog', url: '/blog/best-foods-crohns-flare', tags: ['food', 'flare'] },
  { title: 'Low-Residue Diet During a Flare', category: 'nutrition', type: 'blog', url: '/blog/low-residue-diet-flare', tags: ['food', 'flare'] },
  { title: 'Foods That May Trigger UC Symptoms', category: 'nutrition', type: 'blog', url: '/blog/foods-that-may-trigger-uc-symptoms', tags: ['food'] },
  { title: 'Hydration Tips for IBD', category: 'nutrition', type: 'blog', url: '/blog/hydration-tips-ibd', tags: ['hydration'] },
  { title: 'How Nutrition Impacts Gut Health', category: 'nutrition', type: 'blog', url: '/blog/how-nutrition-impacts-gut-health-ibd', tags: ['food'] },
  { title: 'Flare First 48 Hours', category: 'wellness', type: 'blog', url: '/blog/flare-first-48-hours', tags: ['flare', 'urgent'] },
  { title: 'Workplace & School Rights with IBD', category: 'wellness', type: 'blog', url: '/blog/workplace-school-ibd-rights', tags: ['ada', '504'] },
  { title: 'Insurance & Biologics (Overview)', category: 'treatment', type: 'blog', url: '/blog/insurance-biologics-ibd', tags: ['insurance'] },
  { title: 'Living With an Ostomy', category: 'wellness', type: 'blog', url: '/blog/ostomy-basics-ibd', tags: ['ostomy'] },
  { title: 'Partner & Caregiver Guide', category: 'family', type: 'blog', url: '/blog/partner-caregiver-ibd', tags: ['caregiver'] },
  { title: 'Understanding Biologics', category: 'treatment', type: 'blog', url: '/blog/understanding-biologics-ibd', tags: ['medication'] },
  { title: 'Travel With IBD', category: 'wellness', type: 'blog', url: '/blog/travel-with-ibd', tags: ['travel'] },
  { title: 'Stress, Mood, and IBD', category: 'wellness', type: 'blog', url: '/blog/stress-emotional-wellness-ibd', tags: ['mental health'] },
  { title: 'Sleep and Rest During Flares', category: 'wellness', type: 'blog', url: '/blog/sleep-rest-ibd-flares', tags: ['sleep'] },
  { title: 'Living With IBD as a Family', category: 'family', type: 'blog', url: '/blog/living-with-ibd-kids', tags: ['kids'] },
  { title: 'Introducing IBDPal', category: 'getting-started', type: 'blog', url: '/blog/introducing-ibdpal', tags: ['app'] },
  { title: 'Recursos en español', category: 'community', type: 'site', url: '/es/recursos', tags: ['spanish'] }
];
