# --- 2) Drug x life (8) ---
DRUGS = [
    dict(
        slug="humira-fatigue-ibd", title="Humira (Adalimumab) and Fatigue: What Patients Ask",
        description="Humira and fatigue with Crohn's or colitis: injection timing, anemia, infection signs, and clinic questions. Education only.",
        category="Treatment · August 2026", date_display="August 14, 2026", date_iso="2026-08-14T22:00:00Z",
        asset_dir="humira-fatigue", resource_category="treatment",
        tags=["Humira", "adalimumab", "fatigue", "biologic", "Crohn's", "colitis"],
        lead="Searches for Humira fatigue are extremely common. Tiredness can come from active IBD, anemia, sleep loss, infection, or adjustment periods after starting a biologic. This page helps you prepare questions, not change doses on your own.",
        h2_context="Why fatigue shows up on biologics", context="Adalimumab targets TNF pathways used in Crohn's and UC care.",
        points=["Ongoing inflammation still draining energy", "Iron or B12 deficiency overlapping therapy", "Injection-day malaise in some people", "Infection risk needing fever checks", "Depression and poor sleep amplifying fatigue"],
        h2_action="Practical steps",
        actions=["Log energy 1 to 10 around injection days", "Ask for CBC, iron studies, B12, vitamin D if not recent", "Report fever, cough, or wound issues promptly", "Review injection technique and storage with nursing educators"],
        action_note="Never stop Humira suddenly without your prescriber. See our biologics overview for broader context.",
        urgent=["Fever or chills on immunosuppression", "Chest pain, severe shortness of breath", "Fainting or black stools"],
        myths=[("Humira always causes permanent fatigue.", "Many people feel better as inflammation falls."),
               ("Fatigue means the drug failed.", "Other fixable causes are common."),
               ("More coffee fixes biologic fatigue.", "Treat root causes with your team.")],
        questions=["Should we check labs for anemia?", "Is my dose timing optimized?", "When do we consider therapy change vs supportive care?"],
        related=[("/blog/understanding-biologics-ibd", "biologics overview"), ("/blog/ibd-fatigue-brain-fog", "fatigue"), ("/blog/starting-biologic-first-12-weeks", "first 12 weeks")],
    ),
    dict(
        slug="stelara-diet-ibd", title="Stelara (Ustekinumab) and Diet: Eating While on Therapy",
        description="Stelara and diet with IBD: what to eat during induction, alcohol questions, nutrition goals, and clinic tips. Education only.",
        category="Treatment · August 2026", date_display="August 14, 2026", date_iso="2026-08-14T23:00:00Z",
        asset_dir="stelara-diet", resource_category="treatment",
        tags=["Stelara", "ustekinumab", "diet", "biologic", "nutrition", "Crohn's", "colitis"],
        lead="People starting Stelara often ask what they can eat. No universal Stelara diet exists. Food still follows flare versus remission rules while the medicine works on inflammation.",
        h2_context="Diet goals on ustekinumab", context="Stelara is an IL-12/23 pathway biologic used in IBD.",
        points=["Keep protein and calories up if underweight", "Use gentler textures during residual flares", "Alcohol limits belong in a clinician conversation", "Food does not replace scheduled infusions or injections", "Track triggers so you do not over-restrict forever"],
        h2_action="Eating while therapy ramps up",
        actions=["Pair infusion weeks with easy proteins: eggs, yogurt, fish, smooth shakes if approved", "Hydrate and mind fiber form", "Ask about vaccines and infections before major diet experiments", "Bring a dietitian into the plan for weight regain"],
        action_note="Marketing Stelara diets online are not official protocols.",
        urgent=["Allergic symptoms after dosing", "Fever", "Severe abdominal pain"],
        myths=[("Special juices activate Stelara.", "False."),
               ("You must go vegan on Stelara.", "Not required."),
               ("Diet failure means biologic failure.", "They measure different things.")],
        questions=["Any food or alcohol limits with my other meds?", "Should I use ONS while waiting for response?", "When can I liberalize fiber?"],
        related=[("/blog/understanding-biologics-ibd", "biologics"), ("/blog/protein-shakes-ons-ibd", "ONS"), ("/ibd-nutrition", "nutrition hub")],
    ),
    dict(
        slug="skyrizi-patient-questions-ibd", title="Skyrizi (Risankizumab) for IBD: Patient Questions Beyond the Ad",
        description="Skyrizi for Crohn's: what patients ask about dosing schedule, fatigue, infections, labs, and clinic follow-up. Education only.",
        category="Treatment · August 2026", date_display="August 15, 2026", date_iso="2026-08-15T00:00:00Z",
        asset_dir="skyrizi-ibd", resource_category="treatment",
        tags=["Skyrizi", "risankizumab", "biologic", "IL-23", "Crohn's"],
        lead="Skyrizi searches rose as IL-23 medicines expanded in IBD care. Ads do not answer bathroom logistics, fatigue, or infection rules. Use this as a question list for your gastroenterologist.",
        h2_context="Themes patients bring to clinic", context="Risankizumab targets IL-23 pathways used in Crohn's treatment plans.",
        points=["Induction versus maintenance timing", "Injection training and travel with devices", "Infection screening before start", "How response is judged using symptoms, calprotectin, and scopes", "Insurance and prior authorization delays"],
        h2_action="Prepare your visit",
        actions=["Write top three goals such as pain, urgency, and work attendance", "List prior biologics and why they stopped", "Ask about monitoring labs and vaccines", "Plan a bathroom strategy for induction weeks"],
        action_note="Indications and dosing evolve. Your label and clinician override any blog.",
        urgent=["Signs of serious infection", "Severe allergic reaction", "Black stools or heavy bleeding"],
        myths=[("Skyrizi works overnight for everyone.", "Response timelines vary."),
               ("You can skip doses if you feel well.", "Adherence plans matter."),
               ("Natural IL-23 blockers replace it.", "Unproven marketing.")],
        questions=["Am I a candidate based on prior drugs?", "How will we define success at week X?", "What infections should I watch for?"],
        related=[("/blog/prior-authorization-biologics-timeline", "prior auth"), ("/blog/starting-biologic-first-12-weeks", "first 12 weeks"), ("/blog/vaccines-biologics-immunosuppressants-ibd", "vaccines")],
    ),
    dict(
        slug="rinvoq-patient-questions-ibd", title="Rinvoq (Upadacitinib) and IBD: Patient Questions on JAK Therapy",
        description="Rinvoq for ulcerative colitis or Crohn's contexts: pills vs biologics, infection and lab monitoring questions, education only.",
        category="Treatment · August 2026", date_display="August 15, 2026", date_iso="2026-08-15T01:00:00Z",
        asset_dir="rinvoq-ibd", resource_category="treatment",
        tags=["Rinvoq", "upadacitinib", "JAK inhibitor", "ulcerative colitis", "Crohn's"],
        lead="Rinvoq is an oral JAK inhibitor discussed in IBD clinics. Patients search side effects, labs, and whether pills are safer than infusions. Safety monitoring is part of the therapy, not optional fine print.",
        h2_context="What to understand before starting", context="JAK inhibitors have specific boxed warnings and monitoring frameworks clinicians follow.",
        points=["Oral dosing convenience versus monitoring burden", "Infection, cardiovascular, and clot risk discussions individualized", "Lab checks before and during therapy", "Drug interactions including some supplements", "Not a DIY alternative to biologics without specialist oversight"],
        h2_action="Question checklist",
        actions=["Ask why JAK therapy fits your disease after other options", "Clarify lab schedule and vaccine rules", "Review blood clot and heart risk factors honestly", "Plan contraception discussions if relevant"],
        action_note="Never start or share leftover JAK pills. Prescribing is specialized.",
        urgent=["Chest pain, leg swelling, sudden shortness of breath", "Fever", "Severe abdominal pain"],
        myths=[("Pills have no immune effects.", "False."),
               ("Labs are optional if you feel fine.", "Monitoring is required."),
               ("Online protocols replace GI dosing.", "Dangerous.")],
        questions=["What baseline labs and heart history do you need?", "How does Rinvoq compare to my prior biologic?", "What symptoms mean stop and call?"],
        related=[("/blog/understanding-biologics-ibd", "immune therapies overview"), ("/blog/thrombosis-clot-risk-ibd", "clot risk"), ("/blog/vaccines-biologics-immunosuppressants-ibd", "vaccines")],
    ),
    dict(
        slug="remicade-infusion-day-tips-ibd", title="Remicade (Infliximab) Infusion Day: Patient Tips That Actually Help",
        description="Remicade infusion day tips for IBD: timing, packing, premed questions, afterward fatigue, and clinic logistics. Education only.",
        category="Treatment · August 2026", date_display="August 15, 2026", date_iso="2026-08-15T02:00:00Z",
        asset_dir="remicade-tips", resource_category="treatment",
        tags=["Remicade", "infliximab", "infusion", "biologic", "Crohn's", "colitis"],
        lead="Remicade infusion days are a logistics puzzle: parking, IV time, work notes, and post-infusion fatigue. Pair this with our general infusion-day guide for packing lists.",
        h2_context="What makes infliximab days unique", context="Infliximab is typically an IV TNF biologic given in an infusion center.",
        points=["Chair time longer than home injections", "Premeds sometimes used per protocol", "Reaction monitoring during infusion", "Scheduling around school, work, and travel", "Biosimilar switches may change center routines"],
        h2_action="Day-of tips",
        actions=["Eat a tolerated meal unless told to fast", "Bring layers, charger, and bathroom kit", "Arrange a ride if you feel wiped afterward", "Report itching, chest tightness, or fever during infusion immediately"],
        action_note="Follow your infusion center's instructions over any blog checklist.",
        urgent=["Signs of infusion reaction", "Severe delayed rash with fever", "Black stools or heavy bleeding after"],
        myths=[("Infusions detox the gut.", "They deliver medicine."),
               ("Missing one infusion never matters.", "Gaps can risk flares and antibodies; call the clinic."),
               ("Biosimilars are fake Remicade.", "Regulated alternatives; discuss switches with your team.")],
        questions=["What premeds do I need?", "How do we handle missed appointments?", "Any labs before next infusion?"],
        related=[("/blog/infusion-day-what-to-expect", "infusion day"), ("/blog/understanding-biologics-ibd", "biologics"), ("/blog/insurance-biologics-ibd", "insurance")],
    ),
    dict(
        slug="prednisone-diet-hunger-ibd", title="Prednisone Hunger and Diet With IBD: Surviving Steroid Appetite",
        description="Prednisone hunger with Crohn's or colitis: why appetite surges, gentler food swaps, blood sugar notes, and taper questions. Education only.",
        category="Treatment · August 2026", date_display="August 15, 2026", date_iso="2026-08-15T03:00:00Z",
        asset_dir="prednisone-diet", resource_category="treatment",
        tags=["prednisone", "steroids", "hunger", "diet", "weight", "Crohn's", "colitis"],
        lead="Prednisone can turn appetite into a freight train while your gut is still healing. The goal is enough protein and gentler carbs without living on pure sugar, plus a clear taper plan from your clinician.",
        h2_context="Why steroids change eating", context="Glucocorticoids affect appetite, fluid, mood, and glucose.",
        points=["True hunger plus cravings", "Fluid retention mistaken for fat overnight", "Sleep disruption driving midnight snacks", "Reflux or thrush changing what feels safe", "Bone and glucose risks with longer courses"],
        h2_action="Food tactics during a course",
        actions=["Anchor plates with eggs, yogurt, fish, turkey, or shakes if approved", "Keep soft starch ready: rice, potato, white bread", "Limit sugar-alcohol diet candies that loosen stools", "Do not start extreme cutting diets mid-taper without guidance"],
        action_note="See steroid and taper articles for medical context beyond food.",
        urgent=["Severe mood changes or thoughts of self-harm", "High fever", "Vomiting blood or black stools"],
        myths=[("Hunger means you can stop prednisone early.", "Only taper with your prescriber."),
               ("Starving offsets steroids.", "Undereating harms healing."),
               ("Steroid weight never leaves.", "Many people reclaim habits after taper with support.")],
        questions=["How fast will we taper?", "Do I need glucose monitoring?", "Calcium and vitamin D while on steroids?"],
        related=[("/blog/steroids-prednisone-ibd", "prednisone basics"), ("/blog/steroid-taper-what-to-expect-ibd", "taper"), ("/blog/calcium-ibd", "calcium")],
    ),
    dict(
        slug="methotrexate-alcohol-folate-ibd", title="Methotrexate, Alcohol, and Folate in IBD: Patient Safety Basics",
        description="Methotrexate with IBD: alcohol questions, folic acid schedules, liver labs, and pregnancy warnings. Education only.",
        category="Treatment · August 2026", date_display="August 15, 2026", date_iso="2026-08-15T04:00:00Z",
        asset_dir="mtx-alcohol", resource_category="treatment",
        tags=["methotrexate", "alcohol", "folate", "folic acid", "liver", "Crohn's", "colitis"],
        lead="Methotrexate searches often pair with alcohol and folate. Liver monitoring, infection rules, and pregnancy prevention are core safety topics your rheumatology or GI team will personalize.",
        h2_context="Why these three travel together", context="Methotrexate is an immunomodulator sometimes used in IBD care pathways.",
        points=["Folic acid is commonly prescribed to reduce certain side effects", "Alcohol plus methotrexate raises liver concern discussions", "Lab monitoring is routine", "Pregnancy and breastfeeding rules are strict", "Interactions with some antibiotics and NSAIDs need review"],
        h2_action="Safety checklist",
        actions=["Clarify your exact folic acid schedule (often not on MTX day)", "Ask your clinician's alcohol guidance for your liver history", "Keep lab appointments", "Use reliable contraception if applicable and discuss planning early"],
        action_note="Do not adjust methotrexate from internet alcohol charts. Ask your prescriber.",
        urgent=["Yellowing eyes, severe abdominal pain, unusual bleeding", "Fever with mouth sores", "Shortness of breath"],
        myths=[("A little wine is always fine for everyone on MTX.", "Individual liver risk differs."),
               ("Skip folate to make MTX stronger.", "Dangerous and incorrect."),
               ("MTX is chemotherapy so hair always falls out at IBD doses.", "Dosing contexts differ; report side effects.")],
        questions=["What alcohol limit, if any, fits my labs?", "Confirm my folate dose and timing", "Which symptoms mean hold the dose and call?"],
        related=[("/blog/folate-ibd", "folate"), ("/blog/alcohol-caffeine-ibd", "alcohol overview"), ("/blog/immunosuppressants-ibd-basics", "immunomodulators")],
    ),
    dict(
        slug="biologics-flying-travel-ibd", title="Flying With Biologics: Coolers, Letters, and Airport Tips for IBD",
        description="Traveling by air with IBD biologics: cooler packs, TSA letters, time zones, and infusion timing. Education only.",
        category="Treatment · August 2026", date_display="August 15, 2026", date_iso="2026-08-15T05:00:00Z",
        asset_dir="biologics-travel", resource_category="treatment",
        tags=["biologics", "travel", "flying", "airport", "cooler", "Crohn's", "colitis"],
        lead="Flying with injectables or planning infusions around trips is a top global search for IBD travelers. A little paperwork prevents a lot of panic at security.",
        h2_context="What to arrange before you fly", context="Biologics often need temperature control and documentation.",
        points=["Manufacturer travel letters and original labeled packaging", "Cooler packs that keep medicine in labeled range (not frozen solid unless instructed)", "Carry-on only for injectables", "Time-zone dosing plan with your clinic", "Infusion centers or bridge plans for long trips"],
        h2_action="Airport and cabin tips",
        actions=["Arrive early; declare medical liquids calmly", "Pack spare needles per local rules and script", "Keep a medication list and clinician contact", "Hydrate and map bathrooms after landing"],
        action_note="Pair with our general travel article for restroom and heat strategies.",
        urgent=["Medicine left unrefrigerated beyond labeled limits: call pharmacy or clinic before injecting", "Allergic symptoms after delayed dose catch-up", "Severe flare abroad: know local ER plans"],
        myths=[("Checked bags are safer for biologics.", "Carry-on is usually preferred."),
               ("Ice packs are always banned.", "Medical coolers are commonly allowed with declaration."),
               ("Skipping two doses for vacation is fine.", "Ask before holding therapy.")],
        questions=["Can you provide a travel letter?", "How do I shift injection day across time zones?", "What if customs questions my syringes?"],
        related=[("/blog/travel-with-ibd", "travel with IBD"), ("/blog/summer-travel-ibd-restrooms-meds-food-heat", "summer travel"), ("/blog/starting-biologic-first-12-weeks", "biologic start")],
    ),
]


def build_drug_posts():
    out = []
    for d in DRUGS:
        meta = {k: d[k] for k in ("slug", "title", "description", "category", "date_display", "date_iso", "asset_dir", "resource_category", "tags")}
        meta["share"] = d["description"][:110]
        out.append(post(meta, edu_body(d)))
    return out
