# --- 3) Mythbusters / viral diet claims (6) ---
MYTHS = [
    dict(
        slug="carnivore-diet-ibd-myths", title="Carnivore Diet and IBD: Myths, Risks, and What Evidence Says",
        description="Carnivore diet myths with Crohn's or colitis: protein claims, fiber absence, nutrient gaps, and clinic questions. Education only.",
        category="Nutrition · August 2026", date_display="August 15, 2026", date_iso="2026-08-15T06:00:00Z",
        asset_dir="carnivore-myth", resource_category="nutrition",
        tags=["carnivore diet", "meat only", "myths", "Crohn's", "colitis", "nutrition"],
        lead="Carnivore diet content often promises to heal IBD by cutting every plant food. Inflammation control still belongs with your gastroenterology plan. This page separates marketing slogans from practical nutrition questions.",
        h2_context="What the carnivore pitch claims", context="All-meat plans remove fiber, most plant micronutrients, and usual carbohydrate sources.",
        points=["Anecdotes of short-term symptom calm are not the same as mucosal healing", "Zero fiber can feel easier during a flare but is not a lifelong evidence-based IBD diet", "Iron and protein may rise while vitamin C, folate, and magnesium often fall without planning", "Constipation, lipid changes, and kidney stone risk discussions appear in clinic visits", "Strict exclusion can shrink food variety and raise anxiety around eating"],
        h2_action="Safer framing if you are curious",
        actions=["Ask whether a supervised, temporary low-residue phase fits your flare, not a permanent carnivore identity", "Keep prescribed medicines and monitoring on schedule", "Review labs for anemia, lipids, and vitamin status before extreme restriction", "Work with an IBD-aware dietitian if you need higher protein without cutting all plants forever"],
        action_note="Online carnivore challenges are not clinical protocols. Do not stop biologics or other therapy because a influencer said meat cured them.",
        urgent=["Black stools, heavy bleeding, or fainting", "Rapid weight loss with inability to keep food down", "Chest pain or severe dehydration"],
        myths=[("Carnivore cures Crohn's.", "No high-quality evidence supports that claim."),
               ("All plants inflame the gut.", "Tolerance is individual; many plant foods are used in remission diets."),
               ("If meat feels better, fiber is poison forever.", "Texture and portion often matter more than a permanent ban.")],
        questions=["Is a short low-residue plan appropriate for my current flare?", "Which micronutrients should we monitor if I restrict plants?", "How do we rebuild a balanced plate in remission?"],
        related=[("/ibd-nutrition", "nutrition hub"), ("/blog/fiber-and-ibd-diet", "fiber and IBD"), ("/blog/protein-shakes-ons-ibd", "protein and ONS")],
    ),
    dict(
        slug="bone-broth-gut-healing-ibd", title="Bone Broth and IBD: Gut Healing Claims Versus Reality",
        description="Bone broth for Crohn's or colitis: collagen marketing, hydration value, sodium caveats, and dietitian questions. Education only.",
        category="Nutrition · August 2026", date_display="August 15, 2026", date_iso="2026-08-15T07:00:00Z",
        asset_dir="bone-broth", resource_category="nutrition",
        tags=["bone broth", "collagen", "gut healing", "myths", "Crohn's", "colitis", "nutrition"],
        lead="Bone broth is marketed as a gut sealant for IBD. Warm broth can be soothing and hydrating for some people. It is not a biologic, steroid, or endoscopy-proven healing protocol.",
        h2_context="What broth actually provides", context="Simmered bones yield protein fragments, minerals in modest amounts, and often a lot of salt.",
        points=["Comfort and fluid intake can help when solid food feels hard", "Collagen peptides in broth are not the same as targeted IBD drugs", "Store brands vary widely in sodium and added onion or garlic", "Broth alone rarely meets calorie and protein needs during underweight flares", "Food safety matters with long home simmering and leftovers"],
        h2_action="How to use broth thoughtfully",
        actions=["Treat broth as a gentle fluid or soup base, not a cure", "Check labels if FODMAP-sensitive aromatics bother you", "Pair with tolerated carbs and protein if weight is low", "Ask your team before relying on broth as primary nutrition"],
        action_note="See collagen supplement education for related marketing claims. Prescribed therapy still leads inflammation care.",
        urgent=["Fever with severe abdominal pain after homemade broth (foodborne illness concern)", "Swelling or breathing trouble if you have known meat or additive allergies", "Black stools or heavy bleeding"],
        myths=[("Bone broth seals leaky gut in IBD.", "Marketing phrase; IBD healing is judged clinically."),
               ("Daily broth replaces protein shakes or meals.", "Calories and complete nutrition usually fall short."),
               ("Homemade broth is risk-free.", "Sodium, spices, and food safety still matter.")],
        questions=["Does broth fit my current sodium and FODMAP limits?", "How should I build calories beyond soup?", "Any interaction with my medicines or labs?"],
        related=[("/blog/collagen-supplements-ibd", "collagen supplements"), ("/blog/electrolytes-flare-ibd", "electrolytes"), ("/ibd-nutrition", "nutrition hub")],
    ),
    dict(
        slug="juice-cleanse-detox-ibd", title="Juice Cleanses and Detox Diets With IBD: Why They Backfire",
        description="Juice cleanses and detox myths with Crohn's or colitis: sugar load, fiber loss, malnutrition risk, and safer hydration. Education only.",
        category="Nutrition · August 2026", date_display="August 15, 2026", date_iso="2026-08-15T08:00:00Z",
        asset_dir="juice-detox", resource_category="nutrition",
        tags=["juice cleanse", "detox", "myths", "Crohn's", "colitis", "nutrition"],
        lead="Detox juice searches spike whenever IBD symptoms feel out of control. Your liver and kidneys already handle detoxification. Multi-day juice-only plans can worsen energy, diarrhea, and nutrient gaps.",
        h2_context="What cleanses remove and add", context="Juice strips most pulp fiber while concentrating fruit sugars and plant acids.",
        points=["Rapid calorie drop risks fatigue and muscle loss", "High sugar liquids can loosen stools for some people", "Missing protein slows recovery when the gut is inflamed", "Detox teas and laxative juices can dehydrate you", "Social media before-and-after photos are not endoscopy results"],
        h2_action="Gentler alternatives",
        actions=["Hydrate with water, oral rehydration if advised, and tolerated fluids", "Use smooth textures and soft solids per your flare plan instead of juice-only days", "Keep protein in the rotation if your team allows shakes or soft foods", "Skip unregulated detox kits sold as IBD cures"],
        action_note="Education only. Seek care for dehydration or inability to keep fluids down rather than starting a cleanse.",
        urgent=["Dizziness, very low urine output, or fainting", "Bloody diarrhea with weakness", "Severe vomiting preventing fluid intake"],
        myths=[("Juice flushes IBD toxins.", "No evidence supports toxin-flush cures for Crohn's or UC."),
               ("A week of juice resets the immune system.", "Immune-targeted medicines are prescribed therapies."),
               ("If you feel light at first, it is working.", "Lightheadedness can signal underfueling or dehydration.")],
        questions=["What fluid and electrolyte plan fits my flare?", "How do we protect weight without a cleanse?", "Which soft foods are safer than juice-only days?"],
        related=[("/blog/electrolytes-flare-ibd", "electrolytes"), ("/blog/white-rice-ibd-flare", "white rice"), ("/flare-help", "flare help")],
    ),
    dict(
        slug="intermittent-fasting-ibd", title="Intermittent Fasting and IBD: Hype, Hunger, and Flare Timing",
        description="Intermittent fasting with Crohn's or colitis: meal windows, underweight risks, medication timing, and clinic questions. Education only.",
        category="Nutrition · August 2026", date_display="August 15, 2026", date_iso="2026-08-15T09:00:00Z",
        asset_dir="if-fasting", resource_category="nutrition",
        tags=["intermittent fasting", "IF", "meal timing", "myths", "Crohn's", "colitis", "nutrition"],
        lead="Intermittent fasting is popular for metabolic health headlines. With IBD, long fasting windows can clash with underweight status, steroid hunger, and medicine schedules. Timing food is not the same as treating inflammation.",
        h2_context="Where fasting ideas collide with IBD", context="Skipping meals changes energy intake, glucose patterns, and sometimes symptom perception.",
        points=["People who need weight regain often do poorly with aggressive windows", "Prednisone appetite and fasting plans frequently conflict", "Some oral medicines need food; confirm with pharmacy guidance", "Hunger plus urgency can make work and school days harder", "Research on fasting as IBD therapy remains limited and individualized"],
        h2_action="If you want structure without extremes",
        actions=["Ask whether a regular meal pattern beats prolonged fasting for your weight and labs", "Align any time-restricted eating with your clinician and dietitian", "Do not fast through warning signs of obstruction or dehydration", "Prioritize protein and calories inside whatever window you use"],
        action_note="Viral 20-hour fasts are not standard IBD care. Stop and call your team if pain, vomiting, or inability to eat escalate.",
        urgent=["Vomiting with severe pain (obstruction concern)", "Fainting or confusion from underfueling", "Black stools or heavy bleeding"],
        myths=[("Fasting rests and heals the colon.", "Bowel rest strategies belong in medical settings, not influencer charts."),
               ("Autophagy fasting replaces biologics.", "False and dangerous framing."),
               ("Skipping breakfast always reduces flares.", "Evidence does not support that rule for IBD.")],
        questions=["Does my BMI and lab picture support any fasting pattern?", "How should I time medicines with meals?", "What calorie floor should I hit daily?"],
        related=[("/blog/prednisone-diet-hunger-ibd", "prednisone hunger"), ("/blog/protein-shakes-ons-ibd", "ONS"), ("/ibd-nutrition", "nutrition hub")],
    ),
    dict(
        slug="collagen-supplements-ibd", title="Collagen Supplements and IBD: What Marketing Omits",
        description="Collagen peptides for Crohn's or colitis: joint and skin claims, gut healing ads, protein context, and clinic questions. Education only.",
        category="Nutrition · August 2026", date_display="August 15, 2026", date_iso="2026-08-15T10:00:00Z",
        asset_dir="collagen-ibd", resource_category="nutrition",
        tags=["collagen", "supplements", "peptides", "myths", "Crohn's", "colitis", "nutrition"],
        lead="Collagen powders are sold as gut lining repair for IBD. Collagen is a protein source some people tolerate in shakes. Ads that promise to reverse Crohn's or UC overstate what a supplement can do.",
        h2_context="What collagen can and cannot do", context="Hydrolyzed collagen provides amino acids; it is not a targeted anti-inflammatory drug.",
        points=["May add protein when appetite is low, if your clinician agrees", "Does not replace iron, B12, or vitamin D repletion plans", "Flavored tubs may include sugar alcohols or additives that loosen stools", "Quality and dosing claims vary across brands", "Joint comfort anecdotes are not the same as endoscopic healing"],
        h2_action="Practical supplement hygiene",
        actions=["Bring the label to your visit or pharmacist review", "Count collagen toward total protein, not as magic healing grams", "Prefer simple ingredient lists if additives trigger you", "Keep biologics, mesalamine, or other prescribed therapy unchanged"],
        action_note="Pair with bone broth education if you are comparing liquid versus powder collagen marketing.",
        urgent=["Allergic symptoms after a new powder", "Severe abdominal pain or black stools", "Unexplained swelling or breathing difficulty"],
        myths=[("Collagen rebuilds the intestinal barrier in IBD.", "Unproven as disease-modifying therapy."),
               ("More scoops heal faster.", "Extra powder is still just protein and calories."),
               ("Collagen means you can ignore dietitian advice.", "Overall eating pattern still matters.")],
        questions=["Is collagen appropriate with my kidney and protein goals?", "Any additive concerns on this brand?", "How else should I hit protein targets?"],
        related=[("/blog/bone-broth-gut-healing-ibd", "bone broth"), ("/blog/protein-shakes-ons-ibd", "protein shakes"), ("/blog/zinc-ibd", "zinc")],
    ),
    dict(
        slug="leaky-gut-protocol-ibd", title="Leaky Gut Protocols and IBD: Separating Science From Sales Pages",
        description="Leaky gut protocols with Crohn's or colitis: permeability science, supplement stacks, elimination extremes, and GI questions. Education only.",
        category="Nutrition · August 2026", date_display="August 15, 2026", date_iso="2026-08-15T11:00:00Z",
        asset_dir="leaky-gut", resource_category="nutrition",
        tags=["leaky gut", "intestinal permeability", "protocol", "myths", "Crohn's", "colitis", "nutrition"],
        lead="Leaky gut is a popular label for intestinal permeability. Crohn's and ulcerative colitis involve real barrier and immune problems that specialists already treat. Multi-step online protocols with long supplement lists are not a substitute for IBD guidelines.",
        h2_context="Permeability versus protocol culture", context="Research studies measure barrier function; social media sells 30-day stacks and food fear.",
        points=["Increased permeability can occur with inflammation; treating disease activity is the clinical priority", "Random L-glutamine, zinc, and herbal stacks need safety review, especially on immunosuppression", "Extreme elimination can cause malnutrition and food-related anxiety", "Calprotectin, CRP, and scopes guide IBD care more than DIY leaky gut quizzes", "IBS-style diets may help overlapping symptoms but do not equal curing IBD"],
        h2_action="Evidence-aligned next steps",
        actions=["Bring symptom and stool logs to your gastroenterologist instead of starting a protocol alone", "Ask before adding supplements that claim to seal the gut", "Use dietitian-guided plans such as supervised FODMAP trials when IBS overlap is present", "Focus on vaccination, infection precautions, and medicine adherence as advised"],
        action_note="Education only. Barrier science is real; unregulated leaky gut cures are not standard IBD therapy.",
        urgent=["Fever with rapid decline on unmonitored supplements", "Severe bleeding or black stools", "Inability to eat after aggressive elimination"],
        myths=[("A leaky gut protocol replaces biologics.", "Dangerous and false."),
               ("Everyone with IBD has the same 12 food toxins.", "Triggers are individual; testing belongs with clinicians."),
               ("Permeability teas heal ulcers.", "No substitute for prescribed care and monitoring.")],
        questions=["How do we measure disease activity beyond internet quizzes?", "Which supplements are safe with my medicines?", "Do I have IBS overlap that needs a supervised diet trial?"],
        related=[("/blog/fodmap-diet-crohns-colitis", "FODMAP overview"), ("/blog/reading-ibd-labs-calprotectin-crp", "calprotectin and CRP"), ("/blog/what-remission-means-ibd", "what remission means")],
    ),
]


def build_myth_posts():
    out = []
    for d in MYTHS:
        meta = {k: d[k] for k in ("slug", "title", "description", "category", "date_display", "date_iso", "asset_dir", "resource_category", "tags")}
        meta["share"] = d["description"][:110]
        out.append(post(meta, edu_body(d)))
    return out
