#!/usr/bin/env python3
"""Download Webshare proxy list and write load-test-proxies.txt (gitignored)."""
from __future__ import annotations

import argparse
import os
import ssl
import sys
from pathlib import Path
from urllib.parse import quote
from urllib.error import URLError
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "load-test-proxies.txt"


def webshare_line_to_url(line: str) -> str:
    """Convert `ip:port:username:password` to Playwright proxy URL."""
    line = line.strip()
    if not line or line.startswith("#"):
        raise ValueError("empty line")
    parts = line.split(":")
    if len(parts) < 4:
        raise ValueError(f"expected ip:port:user:pass, got: {line[:80]}")
    host, port, user = parts[0], parts[1], parts[2]
    password = ":".join(parts[3:])
    return f"http://{quote(user, safe='')}:{quote(password, safe='')}@{host}:{port}"


def download_list(url: str, timeout: float = 60.0) -> list[str]:
    ctx = ssl.create_default_context()
    try:
        with urlopen(Request(url, headers={"User-Agent": "IBDPalProxyFetch/1.0"}), context=ctx, timeout=timeout) as resp:
            body = resp.read().decode("utf-8", errors="replace")
    except ssl.SSLError:
        with urlopen(
            Request(url, headers={"User-Agent": "IBDPalProxyFetch/1.0"}),
            context=ssl._create_unverified_context(),
            timeout=timeout,
        ) as resp:
            body = resp.read().decode("utf-8", errors="replace")
    except URLError as exc:
        raise SystemExit(f"Download failed: {exc}") from exc

    if not body.strip():
        raise SystemExit("Download returned empty body")
    if body.lstrip().startswith("{") or "<html" in body[:200].lower():
        raise SystemExit("Download did not return a proxy list (check URL / plan_id)")

    urls: list[str] = []
    for i, line in enumerate(body.splitlines(), 1):
        line = line.strip()
        if not line:
            continue
        try:
            urls.append(webshare_line_to_url(line))
        except ValueError as exc:
            raise SystemExit(f"Line {i}: {exc}") from exc
    if not urls:
        raise SystemExit("No proxies parsed from download")
    return urls


def main() -> int:
    parser = argparse.ArgumentParser(description="Fetch Webshare proxies for load test")
    parser.add_argument(
        "--url",
        default=os.environ.get("WEBSHARE_DOWNLOAD_URL", ""),
        help="Webshare download URL (Proxy List → Download link)",
    )
    parser.add_argument("--output", type=Path, default=OUT)
    args = parser.parse_args()
    if not args.url.strip():
        print("Set WEBSHARE_DOWNLOAD_URL or pass --url", file=sys.stderr)
        return 2

    urls = download_list(args.url.strip())
    header = (
        "# Auto-generated by fetch_webshare_proxies.py — do not commit\n"
        f"# Proxies: {len(urls)}\n"
    )
    args.output.write_text(header + "\n".join(urls) + "\n", encoding="utf-8")
    print(f"Wrote {len(urls)} proxies to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
